### ISSUE TITLE
no centos-7.2-x86_64, while centos 7.2 is used in many roles

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/packer-templates#20]
centos-7.2-x86_64 has been removed and updated to centos-7.3-x86_64.
many ansible-role-* is still using centos-7.2 box.
we should keep 7.2 maintained until all roles are updated to use 7.3.

**Comment by trombik** [comment]
my understanding is that, unlike *BSD, minor version upgrade should not affetct behaviours in general. there are, of course, exceptions. 7.3 box should be a drop-in replacement. if not, it is a bug, most likely, in roles.

instead, 7.2 should be replaced with 7.3 in all roles.

**Comment by trombik** [comment]
closing because https://github.com/reallyenglish/ansible-role-example/issues/128 should be fixed instead.
