### ISSUE TITLE
default mirrors are used, which causes slow downloading

### ISSUE THREAD

**Issue by mitsururike** [reallyenglish/packer-templates#42]
default mirrors are in the distant places and causes slow downloading.
there are two types of mirrors,
* mirrors used for packer build
* mirrors to install distribution sets and packages

both of them should be configured to use the nearest mirrors.

CentOS chooses the nearest mirror automatically and is not needed to be configured.

**Comment by trombik** [comment]
`packer` accepts `-var 'key=value'`. you can always override `mirror` with whatever you want. when `Jenkinsfile` is created (see #41), appropriate default should be set in the file as the build location is fixed.
